### ISSUE TITLE
FYI: borgmatic bug affecting exported

### ISSUE THREAD

**Issue by spali** [maxim-mityutko/borgmatic-exporter#24]
Just for your information.
1.9.1 and potentially also 1.9.0 of borgmatic won't work with the exporter due https://projects.torsion.org/borgmatic-collective/borgmatic/issues/939, which is actually already fixed and is waiting to be released.

**Comment by maxim-mityutko** [comment]
Thanks for letting me know. I see that 1.9.2 was released shortly after.
